import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Demo On-Demand ISR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>
         This app is to demonstrate On-Demand ISR in Next.js
        </h2>    
            <div>
               <h2>Click the link below</h2>
                   <Link href= { `/products`}>
                            <a className={ styles.grid }>Go to products page &rarr;</a>
                    </Link>
            </div>
      </main>      
    </div>
  )
}
